FROM python:3.9.17

WORKDIR /python
COPY python/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
COPY python/ .

EXPOSE 5000

CMD ["python", "admin.py"]
# docker container run --name ssha -it -v $(pwd)/config:/config -v ~/.ssh:/root/.ssh amirstm/sshproxy_admin