FROM python:3.9.17

WORKDIR /python
COPY python/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
COPY python/ .

EXPOSE 5000

VOLUME /python/config

CMD ["python", "admin.py", "DOCKER"]
# docker container run --name ssha --rm -it -v sshproxy_config:/python/config  amirstm/sshproxy_admin