FROM python:3.9.17

WORKDIR /python
COPY python/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
COPY python/ .

VOLUME /python/config

CMD ["python", "main.py", "DOCKER"]
# docker container run --name sshm -d -v sshproxy_config:/python/config -p 37777:37777 amirstm/sshproxy_main